#include <stdio.h>

int main() 
{
    int a, b, c, d, e, f,g;

    printf("Enter a:");
    scanf("%d", &a);

    printf("Enter b:");
    scanf("%d", &b);

    printf("Enter c:");
    scanf("%d", &c);

    printf("Enter d:");
    scanf("%d", &d);

    printf("Enter e:");
    scanf("%d", &e);

    printf("Enter f:");
    scanf("%d", &f);
    
    printf("enter g:");
    scanf("%d",&g);

    (a>b)
        ?(a>c)
            ?(a>d)
                ?(a>e)
                    ?(a>f)
                        ?(a>g)
                            ?printf("a is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?printf("d is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
            :(c>d)
                ?(c>e)
                    ?(c>f)
                        ?(c>g)
                            ?printf("c is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?printf("d is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
        :(b>c)
            ?(b>d)
                ?(b>e)
                    ?(b>f)
                        ?(b>g)
                            ?printf("b is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?printf("d is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
            :(c>d)
                ?(c>e)
                    ?(c>f)
                        ?(c>g)
                            ?printf("c is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                :(d>e)
                    ?(d>f)
                        ?(d>g)
                            ?printf("d is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big")
                    :(e>f)
                        ?(e>g)
                            ?printf("e is big")
                            :printf("g is big")
                        :(f>g)
                            ?printf("f is big")
                            :printf("g is big");
}